### ISSUE TITLE
SPICE fine-tuning trains to Energy gradient not Force

### ISSUE THREAD

**Issue by tkreiman** [facebookresearch/JMP#1]
I believe the SPICE pre-processing is currently returning the negative of the force. The dft_total_energy gradient is the actual (positive) gradient and thus has to be multiplied by -1 to get the force (see this issue on the spice GitHub https://github.com/openmm/spice-dataset/issues/94). Thus it looks like the data has the negative force as the target (unless I am overlooking this -1 multiplication and it happens somewhere else in the code)

**Comment by nimashoghi** [comment]
Thank you for pointing out the issue regarding the force calculation in the SPICE pre-processing.

We were previously unaware of the issue you linked, and as you mentioned, the current SPICE pre-processing code does not do a -1 multiplication to the gradient to get the force. I have updated the pre-processing code in #2.

However, we'd like to clarify that, in our case, this issue does not affect the training of the model, and our energy and force MAE metrics are also unaffected, as they measure the absolute error between the predicted and true values.

Please let us know if you have any further questions or concerns.
